### ISSUE TITLE
فونت رویین

### ISSUE THREAD

**Issue by ShahriarKh** [modafe5124/Rooyin-in-minecraft#1]
سلام
ریپوی فونت رویین پاک شده؟ از کجا می‌شه فونت رو دانلود کرد؟

**Comment by MDarvishi5124** [comment]
سلام، ببخشید که اینقدر دیر جواب میدم؛ متاسفانه ندیدم
فونت رویین از حالت رایگان خارج شده و دیگه قابل دانلود نیست

**Comment by MohamadDarvishi** [comment]
سلام شهریار. فونت رویین دوباره قراره منتشر بشه و فونت رایگان هم داره که همون فونت هایی بودن که آزاد منتشر شده بودن. می‌تونی کار های من رو دنبال کنی.

**Comment by ShahriarKh** [comment]
عالی! نسخه رایگان رو دانلود کردم.
