### ISSUE TITLE
Modrinth release

### ISSUE THREAD

**Issue by tuxinal** [modafe5124/Rooyin-in-minecraft#2]
با سلام
‏[modrinth](https://modrinth.com) یک سایت معروف برای انواع محتوای مربوط به مایکرافت هست. واقعا پیشنهاد می کنم این پروژه رو اونجا هم در دسترس قرار بدین.

**Comment by MDarvishi5124** [comment]
سلام، در مورد انتشارش تو سایت های دیگه تعلل کردم. لطفا یه سری سایت شبیه این سایت رو گلچین کنین و اینجا بفرستین.(من واقعا امثال این سایت رو نمی‌شناسم و تو جستجوی گوگل هم به چنین سایتی برنخورده بودم)

**Comment by tuxinal** [comment]
به جز modrinth سایت curseforge هم هست. به جز این دو تا من سایت دیگه ای نمی شناسم.  به نظر من modrinth از خیلی لحاظ بهتره.
البته اشاره ای هم بکنم modrinth فقط برای نسخهٔ جاوای بازی هست.

**Comment by MDarvishi5124** [comment]
در فرصتی مناسب همراه با رفع برخی ایراد ها، روی این سایت ها هم منتشر می‌کنم.
من خیلی تلاش داشتم که روی curseforge منتشر کنم؛ ولی به دلایلی که متوجه‌ش هم نشدم ممانعت از انجام این کار می‌کرد. باز نگاه می‌ندازم.

**Comment by MDarvishi5124** [comment]
ریسورس پک تو[modrinth](https://modrinth.com/) قرار داده شده. تو مرحلۀ بازبینی قرار داره.
