### ISSUE TITLE
The font doesn't work properly on versions 1.20.5 and 1.20.6

### ISSUE THREAD

**Issue by astrOtuba** [modafe5124/Rooyin-in-minecraft#3]
![2024-05-08_22 59 36](https://github.com/MDarvishi5124/Rooyin-for-Minecraft/assets/96270746/028ba72c-a462-45c0-87e2-b42f2ede528b)

**Comment by MDarvishi5124** [comment]
Hello. Thank you very much for this report.
In Minecraft 1.20.5, UI changes have been made, which caused these problems.
If you want to edit the file yourself, open the "Default.Json" file from the address below in the zip file and set the size value to 10.5.
`assets/minecraft/font`
I think it's best not to release an update to the package until the changes are a little more stable.

**Comment by MDarvishi5124** [comment]
Another issue!
Some letters in this image are displayed incorrectly. If there is such a problem after changing the size, let me know

**Comment by MDarvishi5124** [comment]
In [version 3.0](https://github.com/MDarvishi5124/Rooyin-for-Minecraft/releases/tag/3.0v) of this resource pack, this problem was solved.
